[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg", "pg-types"]

[[redirects]]
  from = "/api/contacto"
  to = "/.netlify/functions/contacto"
  status = 200